version: '3.5'

services:
  project-management:
    container_name: heybooster
    build: .
    stdin_open: true
    tty: true
    restart: on-failure
    ports:
      - 127.0.0.1:8001:8001

    volumes:
      - .:/heybooster
    networks:
      - project_management-network
  project-management-mongo:
    container_name: project-management-mongo
    image: project-management-mongo
    build: .
    restart: always
    ports:
      - 127.0.0.1:27016:27017
    volumes:
      - ./data:/data/db
    networks:
      - project_management-network

networks:
  project_management-network:
    driver: bridge
